### ISSUE TITLE
Add more validation to publication properties

### ISSUE THREAD

**Issue by Marie000** [RebusFoundation/reader-api#394]
- link, resources, readingOrder: validate that they are Link objects (decide what that means exactly)
- type (what types do we want to support?)
- dateModified : should be a timestamp
- bookEdition: should be a string
- bookFormat: should be one of the accpeted formats
- isbn: should be a string (do we want to check anything else? we could use the isbn-verify package)
- keywords: should be an array of strings (would also accept a single string, but would put it in an array)
- genre: should be a string
- url: should be a string, at least. Might want to validate that it is a url
- encodingFormat (not in metadata, so we are at least checking that it is a string. do we have a list of formats we want to check against?)

**Comment by Marie000** [comment]
@baldurbjarnason let me know if you have opinions about any of the property validations I listed above.

My goal is to make sure that the front-end will know what to expect from these properties. For example, if you wanted to display the 'genre' property somewhere, you would be sure that it is a string and not an array or an object. 

For those that will check against a list of accepted values, I can guess what values we might want to accept and we can easily add / remove later if need be.

**Comment by baldurbjarnason** [comment]
Ah, yeah. Let me see...

My opinions:

* Link objects can also just be a URL string that, preferably should be normalised so that it's all Link objects.
* type: need to do some research on those. I'm sure @zwhnz has an opinion
* isbn: should be a string. Validation could be useful But the front end and the import system would have to do some work to normalise isbns before they are added as publishers use a variety of formats (like 'urn:isbn:0451450523' for example). We should probably normalise the ISBN format anyway.
* encodingFormat: I'm not sure if there's a list we could check against as we don't need to actually support all of the formats that people might list. And the methods people seem to propose for validating the format itself look very messy.

Agree on the rest.

**Comment by Marie000** [comment]
for the Link objects, would it be ok to validate this way:
- must have a url property (with a string)
- can have these properties: encodingFormat, name, description, rel, integrity, length
- other properties will be removed
does that make sense? Or could Link object have other valid fields? I could also only enforce that it has a url string.

**Comment by baldurbjarnason** [comment]
Link objects can also have a type, `LinkedResource`, but yeah otherwise that would work. And if all link objects are normalised to an object even when a url string is passed then I think we got something that will work.
