### ISSUE TITLE
Enable creating and updating notes with tags

### ISSUE THREAD

**Issue by Marie000** [RebusFoundation/reader-api#599]
@baldurbjarnason @cesarCSM 

So the basic idea is that when you create or update a note, you would be able to pass in a 'tags' property, which would be an array of tags to assign to that note. 

Some questions:
- should we be able to create a note with tags that do not yet exist? 
- when updating a note with a 'tags' property, do you want to simply add those tags to the note (and ignore any existing tags) or overwrite the existing tags (so remove any tags that are not on the new list)? 
Another alternative would be to have, isntead of 'tags', 'addTags' and 'removeTags' properties for note updates. That makes things less consistent, but it might make things easier. 
- do you want the 'tags' property to be an array of tagIds or an array of tag objects? Or accept both? 
- Would it be useful to have more specific 'flags', 'stacks' and 'colour' properties?

**Comment by cesarCSM** [comment]
- Yes, the user should be able to create his own tags. The type of this tags should be different from stacks, colours or flags.
- When the user updates a note, he will be able to update (remove/add) or keep the tags of that note
- Baldur is currently working on this part so i think he will have a better answer than me

**Comment by baldurbjarnason** [comment]
1. See Cesar's answer. He knows what the UI plan is better than I do.
2. My preference would be for the tags property to overwrite existing tags (if it isn't in the list, remove it). That way the front end will always know what's supposed to happen when a note is updated.
3. Ideally, the tags property should be able to take a list of either ids or objects. If the object doesn't have an id then that means it is a new tag to be created.
4. Currently, tags are managed as a single block because the front end gets them as a single block (through the `/tags` endpoint) which is easy because they all behave the same. It would only really be useful to add new, more specific, properties if those properties behave differently or have more specific error scenarios.

For example: it would make sense to add a `colour` property if that property only allows for one colour at a time (the current colour of the note). Adding more than one colour would then be an error.

I think it's a bit too early for that as we're still in the middle of a redesign and managing tags together as a single group is still working well.
